import chapter25
sentence = "All good things come to those who wait."
words = chapter25.break_words(sentence)
print(words)
sorted_words = chapter25.sort_words(words)
print(sorted_words)
chapter25.print_first_word(words)
chapter25.print_last_word(words)
print(words)
chapter25.print_first_word(sorted_words)
chapter25.print_last_word(sorted_words)
print(sorted_words)
sorted_words = chapter25.sort_sentence(sentence)
print(sorted_words)
chapter25.print_first_and_last(sentence)
chapter25.print_first_and_last_sorted(sentence)